name: my first github action cicd test
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: give an intro
        run: echo "hello world"
      - name: using maven for build
        run: mvn clean package
